# Generated by Django 4.2.7 on 2023-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phoneNumber",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phoneNumber",
            field=models.IntegerField(max_length=10),
        ),
    ]
