# Generated by Django 4.2.7 on 2024-01-03 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.project"
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="status",
            field=models.CharField(
                choices=[("w", "waiting"), ("r", "rejected"), ("a", "approved")],
                default="w",
                max_length=2,
                null=True,
            ),
        ),
    ]
