# Generated by Django 4.2.7 on 2024-01-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_student_project_alter_suggestion_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requirement",
            name="project",
        ),
        migrations.AddField(
            model_name="requirement",
            name="suggestion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.suggestion",
            ),
            preserve_default=False,
        ),
    ]
