# Generated by Django 4.2.7 on 2024-01-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_requirement_project_requirement_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="main_suggestion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_main_suggestion",
                to="api.suggestion",
            ),
        ),
    ]
