# Generated by Django 4.2.7 on 2024-01-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_project_main_suggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
