# Generated by Django 4.2.7 on 2024-04-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_student_serialnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="first_grading",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="second_grading",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="teacher_grading",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="isExaminer",
            field=models.BooleanField(default=False),
        ),
    ]
