# Generated by Django 5.1.1 on 2024-09-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_first_grading_project_second_grading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
