# Generated by Django 5.1.1 on 2025-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
