# Generated by Django 5.1.1 on 2025-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
