# Generated by Django 5.1.1 on 2025-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department_head_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
