# Generated by Django 5.1.1 on 2025-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_project_coordinator_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_grading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_grading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='teacher_grading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
