# Generated by Django 5.1.1 on 2025-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_first_grading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='coordinator_score',
            new_name='coordinator_grade',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='department_head_score',
            new_name='department_head_grade',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='teacher_grading',
            new_name='supervisor_grade',
        ),
        migrations.AddField(
            model_name='project',
            name='graded_status',
            field=models.CharField(choices=[('not_graded', 'لم يتم جمع الدرجات'), ('partial', 'تم جمع بعض الدرجات'), ('graded', 'تم جمع كل الدرجات')], default='not_graded', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_coordinator',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_examiner1',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_examiner2',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_head',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_supervisor',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
