# Generated by Django 5.1.1 on 2025-07-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_coordinator_score_project_coordinator_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pdf_coordinator',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_examiner1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_examiner2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_head',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pdf_supervisor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
