# Generated by Django 5.1.1 on 2025-07-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_project_pdf_coordinator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pdf_coordinator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf_head',
        ),
    ]
