# Generated by Django 5.1.1 on 2025-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_project_pdf_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='examined_projects',
            field=models.ManyToManyField(blank=True, related_name='examiners', to='api.project'),
        ),
    ]
